name: namo_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  share_plus: ^10.1.3
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.8
  flutter_statusbarcolor_ns: ^0.6.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_web3_provider: ^2.0.2
  provider: ^6.0.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  story: ^1.1.0
  story_view: ^0.16.5
  path_provider: ^2.1.3
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/

    - assets/images/img_apple.png
    - assets/images/img_fb.png
    - assets/images/img_gmail.png
    - assets/images/img_twitter.png
    - assets/images/img_user.png
    - assets/images/img_ems.png
    - assets/images/img_one.jpeg
    - assets/images/no_img.png

    - assets/icons/ic_arrow.png
    - assets/icons/ic_settings.png
    - assets/icons/ic_report.png
    - assets/icons/ic_search.png
    - assets/icons/ic_dashboard.png
    - assets/icons/ic_home.png
    - assets/icons/ic_notification.png
    - assets/icons/ic_language.png
    - assets/icons/ic_round.png

    - assets/icons/ic_mail.png
    - assets/icons/ic_pass.png
    - assets/icons/ic_like.png
    - assets/icons/ic_share.png
    - assets/icons/ic_delete.png
    - assets/icons/ic_attach.png
    - assets/icons/ic_circle.png
    - assets/icons/ic_square.png

